services:
  profileeditor:
    image: ${DOCKER_REGISTRY-}profileeditor
    build:
      context: .
      dockerfile: ProfileEditor/Dockerfile
    ports:
      - "8090:8080"
      - "8091:8081"
    depends_on:
      - db
      - azurite
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ProfileEditor;User Id=sa;Password=${MSSQL_PASS:-Your_Strong_Password123};TrustServerCertificate=True;


  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASS:-Your_Strong_Password123}
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"  # Blob service
      - "10001:10001"  # Queue service
      - "10002:10002"  # Table service
    volumes:
      - ./azurite-data:/data
    restart: unless-stopped

volumes:
  sqldata:
